Update remove nth node from end of the linked list
In the domain of linked lists, a challenging task beckons your coding prowess. You are entrusted with the responsibility of manipulating a linked list by removing the nth node from its end.

Define a structure

ListNode {
               int val;
              ListNode next;
}

Include functions:

    ListNode removeNthFromEnd(ListNode head, int n): This function removes the nth node from the end of the linked list and returns the head node of the modified list.
    void printList(ListNode head): This function prints the elements of the linked list.
Constraints:

    The number of nodes in the list is represented by sz.
    1 <= sz <= 30
    0 <= Node.val <= 100
    1 <= n <= sz
Input:

The input consists of two parts:

    The values for the nodes in the linked list, provided as comma-separated integers.
    The value of n, representing the position of the node to be removed from the end.
Output:

If the removal is successful, print the modified linked list after removing the nth node from the end.
If the removal fails due to invalid input or the absence of the specified node, print an error message indicating the failure.
Input and Output Format:
Refer sample input and output for formatting specifications.

[All text in bold corresponds to input and the rest corresponds to output.]

Sample Input and Output 1:

Enter the node values (comma-separated): 
1,2,3,4,5
Enter the value of n: 
2
Linked List after removing the 2th node from the end:
1 2 3 5

Sample Input and Output 2:

Enter the node values (comma-separated): 
1
Enter the value of n: 
1
Error: Unable to remove the 1th node from the end.